use_frameworks!

target 'SVBlockchain_Example' do
  pod 'SVBlockchain', :path => '../'

  target 'SVBlockchain_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 7.3.1'
    pod 'Stubborn'
  end
end
